services:
  mongodb:
    build:
      context: './src'
      dockerfile: 'Dockerfile'
    volumes:
      - './init:/docker-entrypoint-initdb.d'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017:27017'